import * as fs from 'fs';
import * as path from 'path';

/**
 * Commands understood by the migration CLI (`npm run db:migrate -- <command>`).
 *
 *  - `deploy` — apply pending migrations (`prisma migrate deploy`).
 *  - `status` — report applied / pending migrations (`prisma migrate status`).
 *  - `down <migration>` — execute the migration's hand-written `down.sql` and
 *    remove it from `_prisma_migrations` (in one script) so a later `deploy`
 *    can re-apply it.
 *  - `reset` — drop and recreate the database (`prisma migrate reset`).
 */
export const MIGRATION_COMMANDS = ['deploy', 'status', 'down', 'reset'] as const;
export type MigrationCommand = (typeof MIGRATION_COMMANDS)[number];

/** Commands that can destroy data and are therefore blocked in production. */
export const DESTRUCTIVE_COMMANDS: ReadonlySet<MigrationCommand> = new Set(['down', 'reset']);

/** Flag that overrides the production block for destructive commands. */
export const FORCE_FLAG = '--force';

export interface ParsedMigrationArgs {
  command: MigrationCommand;
  /** Target migration folder name; required for `down`. */
  migration?: string;
  force: boolean;
}

export interface MigrationSafetyDecision {
  allowed: boolean;
  /** Message for stderr: why the command was blocked, or that an override is active. */
  warning?: string;
}

/** Thrown for malformed invocations; the CLI reports it and exits non-zero. */
export class MigrationCliError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MigrationCliError';
  }
}

/** True when `NODE_ENV` names production, tolerating case and whitespace. */
export function isProductionEnv(nodeEnv: string | undefined): boolean {
  return (nodeEnv ?? '').trim().toLowerCase() === 'production';
}

/** Parses CLI arguments (without the node/script prefix). */
export function parseMigrationArgs(argv: readonly string[]): ParsedMigrationArgs {
  const flags = argv.filter((arg) => arg.startsWith('--'));
  const positional = argv.filter((arg) => !arg.startsWith('--'));

  const unknown = flags.filter((flag) => flag !== FORCE_FLAG);
  if (unknown.length > 0) {
    throw new MigrationCliError(`Unknown option(s): ${unknown.join(', ')}`);
  }

  const [command, migration, ...extra] = positional;
  if (!command || !(MIGRATION_COMMANDS as readonly string[]).includes(command)) {
    throw new MigrationCliError(
      `Unknown or missing command '${command ?? ''}'. Expected one of: ${MIGRATION_COMMANDS.join(', ')}`,
    );
  }

  const takesMigration = command === 'down';
  if (takesMigration && !migration) {
    throw new MigrationCliError('down requires a migration name, e.g. `down 20260901080000_add_x`');
  }
  if ((!takesMigration && migration) || extra.length > 0) {
    throw new MigrationCliError(`Unexpected argument(s) for '${command}'`);
  }

  return {
    command: command as MigrationCommand,
    migration: takesMigration ? migration : undefined,
    force: flags.includes(FORCE_FLAG),
  };
}

/**
 * Decides whether a migration command may run in the given environment.
 * Destructive commands are rejected when `NODE_ENV=production` unless
 * `--force` was supplied; non-destructive commands always pass.
 */
export function checkMigrationSafety(
  args: Pick<ParsedMigrationArgs, 'command' | 'force'>,
  env: Readonly<Record<string, string | undefined>>,
): MigrationSafetyDecision {
  if (!DESTRUCTIVE_COMMANDS.has(args.command) || !isProductionEnv(env.NODE_ENV)) {
    return { allowed: true };
  }

  if (!args.force) {
    return {
      allowed: false,
      warning:
        `Refusing to run destructive migration command '${args.command}' while NODE_ENV=production.\n` +
        `This can permanently delete data. Take a verified backup first, then re-run with ` +
        `${FORCE_FLAG} if the rollback is intentional.`,
    };
  }

  return {
    allowed: true,
    warning:
      `WARNING: ${FORCE_FLAG} supplied; running destructive migration command ` +
      `'${args.command}' against a production database.`,
  };
}

/** One `prisma` CLI invocation, optionally fed SQL on stdin. */
export interface PrismaInvocation {
  args: string[];
  stdin?: string;
}

/** Migration folder names are generated by Prisma; anything else is rejected. */
const MIGRATION_NAME = /^[A-Za-z0-9_]+$/;

/**
 * Translates a parsed command into the `prisma` invocations that perform it.
 * For `down`, validates that the migration exists and ships a `down.sql`.
 */
export function buildPrismaInvocations(
  args: ParsedMigrationArgs,
  options: {
    migrationsDir: string;
    schemaPath: string;
    exists: (file: string) => boolean;
    readFile: (file: string) => string;
  },
): PrismaInvocation[] {
  const schema = ['--schema', options.schemaPath];

  switch (args.command) {
    case 'deploy':
      return [{ args: ['migrate', 'deploy', ...schema] }];
    case 'status':
      return [{ args: ['migrate', 'status', ...schema] }];
    case 'reset':
      return [{ args: ['migrate', 'reset', ...schema] }];
    case 'down': {
      const name = args.migration ?? '';
      if (!MIGRATION_NAME.test(name)) {
        throw new MigrationCliError(`Invalid migration name '${name}'`);
      }
      const folder = path.join(options.migrationsDir, name);
      if (!options.exists(path.join(folder, 'migration.sql'))) {
        throw new MigrationCliError(`Migration '${name}' not found in ${options.migrationsDir}`);
      }
      const downFile = path.join(folder, 'down.sql');
      if (!options.exists(downFile)) {
        throw new MigrationCliError(
          `Migration '${name}' has no down.sql. Write one (see docs/database.md) before rolling back.`,
        );
      }
      // One script, so the history row is only removed if every statement in
      // down.sql succeeded; a failed rollback leaves the migration recorded.
      const script =
        `${options.readFile(downFile).trimEnd()}

` +
        `DELETE FROM "_prisma_migrations" WHERE "migration_name" = '${name}';
`;
      return [{ args: ['db', 'execute', '--stdin', ...schema], stdin: script }];
    }
  }
}

export interface MigrationCliDeps {
  env: Readonly<Record<string, string | undefined>>;
  stdout: (line: string) => void;
  stderr: (line: string) => void;
  /** Runs `prisma <args>` and resolves to its exit code. */
  runPrisma: (invocation: PrismaInvocation) => Promise<number>;
  exists?: (file: string) => boolean;
  readFile?: (file: string) => string;
  migrationsDir?: string;
  schemaPath?: string;
}

/**
 * Entry point for the migration CLI. Parses arguments, applies the production
 * safety guard, then dispatches to Prisma. Resolves to the process exit code
 * and never touches the database when a command is blocked.
 */
export async function runMigrationCli(
  argv: readonly string[],
  deps: MigrationCliDeps,
): Promise<number> {
  let parsed: ParsedMigrationArgs;
  let invocations: PrismaInvocation[];
  try {
    parsed = parseMigrationArgs(argv);
    const decision = checkMigrationSafety(parsed, deps.env);
    if (decision.warning) deps.stderr(decision.warning);
    if (!decision.allowed) return 1;

    invocations = buildPrismaInvocations(parsed, {
      migrationsDir: deps.migrationsDir ?? path.join('prisma', 'migrations'),
      schemaPath: deps.schemaPath ?? path.join('prisma', 'schema.prisma'),
      exists: deps.exists ?? fs.existsSync,
      readFile: deps.readFile ?? ((file) => fs.readFileSync(file, 'utf8')),
    });
  } catch (error) {
    if (error instanceof MigrationCliError) {
      deps.stderr(`Error: ${error.message}`);
      deps.stderr(
        `Usage: db:migrate <${MIGRATION_COMMANDS.join('|')}> [migration] [${FORCE_FLAG}]`,
      );
      return 2;
    }
    throw error;
  }

  for (const invocation of invocations) {
    const code = await deps.runPrisma(invocation);
    if (code !== 0) {
      deps.stderr(`prisma ${invocation.args.slice(0, 2).join(' ')} exited with code ${code}`);
      return code;
    }
  }

  if (parsed.command === 'down') {
    deps.stdout(`Rolled back migration '${parsed.migration}'.`);
  }
  return 0;
}
