import { spawnSync } from 'child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join, resolve } from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

/**
 * Exercises `scripts/verify-migrations.sh` against throwaway migration trees.
 * Schema validation and the database tier are disabled here so the suite runs
 * without Prisma engines or Postgres; they are covered by the CI job itself.
 */
const SCRIPT = resolve(__dirname, '..', '..', 'scripts', 'verify-migrations.sh');
const hasBash = spawnSync('bash', ['--version']).status === 0;

const SCHEMA = `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Thing {
  id String @id
}
`;

const LOCK = '# Please do not edit this file manually\nprovider = "postgresql"\n';

describe.skipIf(!hasBash)('scripts/verify-migrations.sh', () => {
  let root: string;
  let migrationsDir: string;

  const write = (relativePath: string, content: string) => {
    const path = join(migrationsDir, relativePath);
    mkdirSync(join(path, '..'), { recursive: true });
    writeFileSync(path, content);
  };

  const git = (...args: string[]) => {
    const result = spawnSync('git', args, { cwd: root, encoding: 'utf8' });
    if (result.status !== 0) {
      throw new Error(`git ${args.join(' ')} failed: ${result.stderr}`);
    }
  };

  const run = (env: Record<string, string> = {}) => {
    const result = spawnSync('bash', [SCRIPT], {
      cwd: root,
      encoding: 'utf8',
      env: {
        ...process.env,
        GITHUB_ACTIONS: '',
        SHADOW_DATABASE_URL: '',
        MIGRATION_BASE_REF: '',
        SKIP_SCHEMA_VALIDATION: 'true',
        MIGRATIONS_DIR: 'prisma/migrations',
        SCHEMA_PATH: 'prisma/schema.prisma',
        ...env,
      },
    });
    return { status: result.status, output: `${result.stdout}${result.stderr}` };
  };

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'astroid-migrations-'));
    migrationsDir = join(root, 'prisma', 'migrations');
    mkdirSync(migrationsDir, { recursive: true });
    writeFileSync(join(root, 'prisma', 'schema.prisma'), SCHEMA);
    write('migration_lock.toml', LOCK);
    write(
      '0_init/migration.sql',
      'CREATE TABLE "Thing" ("id" TEXT NOT NULL, PRIMARY KEY ("id"));\n',
    );
    write('20260101000000_add_name/migration.sql', 'ALTER TABLE "Thing" ADD COLUMN "name" TEXT;\n');
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('passes a well-formed migration history', () => {
    const { status, output } = run();

    expect(output).toContain('Inspected 2 migration folder(s).');
    expect(output).toContain('Migration verification passed');
    expect(status).toBe(0);
  });

  it('accepts comments, strings and dollar-quoted bodies containing SQL punctuation', () => {
    write(
      '20260102000000_trigger/migration.sql',
      [
        '-- a comment with an unbalanced ( and a ;',
        '/* block comment ) ; */',
        `INSERT INTO "Thing" ("id") VALUES ('it''s (fine);');`,
        'CREATE FUNCTION touch() RETURNS trigger AS $body$',
        "BEGIN NEW.name := '('; RETURN NEW; END;",
        '$body$ LANGUAGE plpgsql;',
        '',
      ].join('\r\n'),
    );

    expect(run().status).toBe(0);
  });

  it('fails with an actionable message when a folder lacks migration.sql', () => {
    mkdirSync(join(migrationsDir, '20260102000000_forgotten'));

    const { status, output } = run();

    expect(status).toBe(1);
    expect(output).toContain('20260102000000_forgotten: Missing migration.sql');
  });

  it.each([
    ['an empty file', '', 'contains no SQL statements'],
    ['only comments', '-- TODO\n/* nothing */\n', 'contains no SQL statements'],
    [
      'an unterminated final statement',
      'ALTER TABLE "Thing" ADD COLUMN "x" TEXT\n',
      ':1: Invalid SQL: final statement is not terminated',
    ],
    [
      'an unclosed parenthesis',
      'CREATE TABLE "T" (\n  "id" TEXT;\n',
      ':2: Invalid SQL: statement ends with 1 unclosed "("',
    ],
    ['a stray closing parenthesis', 'SELECT 1);\n', ':1: Invalid SQL: unbalanced ")"'],
    [
      'an unterminated string',
      'INSERT INTO "T" VALUES (\'oops);\n',
      'unterminated string literal (opened on line 1)',
    ],
    ['an unterminated block comment', 'SELECT 1;\n/* never closed\n', 'unterminated /* comment'],
    [
      'a merge-conflict marker',
      'SELECT 1;\n<<<<<<< HEAD\nSELECT 2;\n',
      ':2: Invalid SQL: unresolved merge-conflict marker',
    ],
  ])('rejects a migration.sql with %s', (_label, sql, expected) => {
    write('20260102000000_broken/migration.sql', sql);

    const { status, output } = run();

    expect(status).toBe(1);
    expect(output).toContain('20260102000000_broken/migration.sql');
    expect(output).toContain(expected);
  });

  it('rejects malformed folder names and duplicate timestamps', () => {
    write('add_thing/migration.sql', 'SELECT 1;\n');
    write('20260101000000_clash/migration.sql', 'SELECT 1;\n');

    const { status, output } = run();

    expect(status).toBe(1);
    expect(output).toContain("Invalid migration folder name 'add_thing'");
    expect(output).toContain('Timestamp 20260101000000 is shared with');
  });

  it('rejects a missing lock file and a provider mismatch', () => {
    rmSync(join(migrationsDir, 'migration_lock.toml'));
    expect(run().output).toContain('migration_lock.toml is missing');

    write('migration_lock.toml', 'provider = "mysql"\n');
    const { status, output } = run();
    expect(status).toBe(1);
    expect(output).toContain(
      'provider "mysql" does not match the schema datasource provider "postgresql"',
    );
  });

  it('rejects stray files at the top of the migrations directory', () => {
    write('fix.sql', 'SELECT 1;\n');

    const { status, output } = run();

    expect(status).toBe(1);
    expect(output).toContain('fix.sql: Unexpected file in migrations directory');
  });

  it('reports every error in one run and emits GitHub annotations in CI', () => {
    mkdirSync(join(migrationsDir, '20260102000000_forgotten'));
    write('20260103000000_broken/migration.sql', 'SELECT (1;\n');

    const { status, output } = run({ GITHUB_ACTIONS: 'true' });

    expect(status).toBe(1);
    expect(output).toContain(
      '::error file=prisma/migrations/20260102000000_forgotten::Missing migration.sql',
    );
    expect(output).toContain(
      '::error file=prisma/migrations/20260103000000_broken/migration.sql,line=1::Invalid SQL',
    );
    expect(output).toContain('FAILED: 2 error(s)');
  });

  describe('history checks against MIGRATION_BASE_REF', () => {
    beforeEach(() => {
      git('init', '-q');
      git('config', 'user.email', 'test@example.com');
      git('config', 'user.name', 'test');
      git('config', 'core.autocrlf', 'false');
      git('add', '.');
      git('commit', '-q', '-m', 'base');
      git('tag', 'base');
    });

    it('passes when a new migration is appended', () => {
      write(
        '20260201000000_add_email/migration.sql',
        'ALTER TABLE "Thing" ADD COLUMN "email" TEXT;\n',
      );

      const { status, output } = run({ MIGRATION_BASE_REF: 'base' });

      expect(output).toContain('New migration: 20260201000000_add_email');
      expect(status).toBe(0);
    });

    it('rejects edits to a migration that already exists on the base ref', () => {
      write(
        '20260101000000_add_name/migration.sql',
        'ALTER TABLE "Thing" ADD COLUMN "title" TEXT;\n',
      );

      const { status, output } = run({ MIGRATION_BASE_REF: 'base' });

      expect(status).toBe(1);
      expect(output).toContain(
        "Migration '20260101000000_add_name' already exists on base and was modified",
      );
    });

    it('rejects deleting a migration that exists on the base ref', () => {
      rmSync(join(migrationsDir, '20260101000000_add_name'), { recursive: true });

      const { status, output } = run({ MIGRATION_BASE_REF: 'base' });

      expect(status).toBe(1);
      expect(output).toContain(
        "Migration '20260101000000_add_name' exists on base but was deleted",
      );
    });

    it('rejects a new migration that would be applied out of order', () => {
      write('20251231000000_backdated/migration.sql', 'SELECT 1;\n');

      const { status, output } = run({ MIGRATION_BASE_REF: 'base' });

      expect(status).toBe(1);
      expect(output).toContain(
        "New migration '20251231000000_backdated' sorts before '20260101000000_add_name'",
      );
    });

    it('warns, without failing, on destructive statements in new migrations only', () => {
      write(
        '20260201000000_cleanup/migration.sql',
        '-- DROP TABLE "Thing"; in a comment is ignored\nALTER TABLE "Thing" DROP COLUMN "name";\n',
      );

      const { status, output } = run({ MIGRATION_BASE_REF: 'base' });

      expect(status).toBe(0);
      expect(output).toContain(
        'WARNING: prisma/migrations/20260201000000_cleanup/migration.sql:2: Potentially destructive statement',
      );
      expect(output).not.toContain('migration.sql:1: Potentially destructive');
      expect(output).toContain('passed with 1 warning(s)');
    });

    it('skips with a warning when the base ref cannot be resolved', () => {
      const { status, output } = run({ MIGRATION_BASE_REF: 'origin/does-not-exist' });

      expect(status).toBe(0);
      expect(output).toContain("cannot resolve a merge base with 'origin/does-not-exist'");
    });
  });
});
